export const GET_ALL_POSTS_REQUEST = "GET_ALL_POSTS_REQUEST";
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
export const GET_ALL_POSTS_FAIL = "GET_ALL_POSTS_FAIL";

export const GET_POST_DETAILS_REQUEST = "GET_POST_DETAILS_REQUEST";
export const GET_POST_DETAILS_SUCCESS = "GET_POST_DETAILS_SUCCESS";
export const GET_POST_DETAILS_FAIL = "GET_POST_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
